# Cloud Build configuration for LLM-Connector-Hub
#
# Triggers:
# - Push to main branch -> Deploy to dev
# - Push to release/* branch -> Deploy to staging
# - Git tag v* -> Deploy to prod
#
# Required substitutions:
# - _REGION: Cloud Run region
# - _PLATFORM_ENV: dev | staging | prod
# - _RUVECTOR_SERVICE_URL: RuVector service endpoint
# - _TELEMETRY_ENDPOINT: LLM-Observatory endpoint

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/llm-connector-hub:${_IMAGE_TAG}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/llm-connector-hub:latest'
      - '-f'
      - 'packages/agents/Dockerfile'
      - '.'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/llm-connector-hub:${_IMAGE_TAG}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/llm-connector-hub:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'llm-connector-hub'
      - '--image'
      - 'gcr.io/$PROJECT_ID/llm-connector-hub:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60s'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'SERVICE_NAME=llm-connector-hub,SERVICE_VERSION=${_IMAGE_TAG},PLATFORM_ENV=${_PLATFORM_ENV},RUVECTOR_SERVICE_URL=${_RUVECTOR_SERVICE_URL},TELEMETRY_ENDPOINT=${_TELEMETRY_ENDPOINT},TELEMETRY_ENABLED=true'
      - '--set-secrets'
      - 'RUVECTOR_API_KEY=ruvector-api-key:latest'

  # Step 4: Verify deployment health
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SVC_URL=$$(gcloud run services describe llm-connector-hub --region=${_REGION} --format='value(status.url)')
        echo "Service URL: $$SVC_URL"

        # Health check
        HEALTH_STATUS=$$(curl -s -o /dev/null -w "%{http_code}" "$$SVC_URL/health")
        if [ "$$HEALTH_STATUS" != "200" ]; then
          echo "Health check failed with status: $$HEALTH_STATUS"
          exit 1
        fi
        echo "Health check passed"

        # Ready check
        READY_STATUS=$$(curl -s -o /dev/null -w "%{http_code}" "$$SVC_URL/ready")
        if [ "$$READY_STATUS" != "200" ]; then
          echo "Warning: Readiness check returned status: $$READY_STATUS"
        else
          echo "Readiness check passed"
        fi

substitutions:
  _REGION: 'us-central1'
  _PLATFORM_ENV: 'dev'
  _RUVECTOR_SERVICE_URL: 'https://ruvector-service-xxx.run.app'
  _TELEMETRY_ENDPOINT: 'https://llm-observatory-xxx.run.app'
  _IMAGE_TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/llm-connector-hub:${_IMAGE_TAG}'
  - 'gcr.io/$PROJECT_ID/llm-connector-hub:latest'

timeout: '1200s'
