# Cloud Build configuration for Phase 6 - Core Infrastructure (Layer 1)
#
# Deploys core infrastructure agents to Cloud Run:
# - ConfigValidationAgent (config_validation_signal)
# - SchemaEnforcementAgent (schema_violation_signal)
# - IntegrationHealthAgent (integration_health_signal)
#
# Required secrets in Google Secret Manager:
# - ruvector-api-key: API key for Ruvector service
# - telemetry-api-key: API key for telemetry endpoint (optional)
#
# Required substitutions:
# - _REGION: Cloud Run region
# - _PLATFORM_ENV: dev | staging | prod
# - _RUVECTOR_SERVICE_URL: Ruvector service endpoint
# - _TELEMETRY_ENDPOINT: LLM-Observatory endpoint

steps:
  # Step 1: Build Docker image for core infrastructure
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/core-infrastructure:${_IMAGE_TAG}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/core-infrastructure:latest'
      - '-f'
      - 'deployment/Dockerfile.phase6'
      - '--build-arg'
      - 'SERVICE_VERSION=${_IMAGE_TAG}'
      - '.'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-tagged'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/core-infrastructure:${_IMAGE_TAG}'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/core-infrastructure:latest'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run with secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'core-infrastructure'
      - '--image'
      - 'gcr.io/$PROJECT_ID/core-infrastructure:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60s'
      - '--concurrency'
      - '80'
      # Environment variables
      - '--set-env-vars'
      - 'SERVICE_NAME=core-infrastructure,SERVICE_VERSION=${_IMAGE_TAG},PLATFORM_ENV=${_PLATFORM_ENV},RUVECTOR_SERVICE_URL=${_RUVECTOR_SERVICE_URL},TELEMETRY_ENDPOINT=${_TELEMETRY_ENDPOINT},TELEMETRY_ENABLED=true,NODE_ENV=production,MAX_TOKENS=800,MAX_LATENCY_MS=1500'
      # Secrets from Google Secret Manager
      - '--set-secrets'
      - 'RUVECTOR_API_KEY=ruvector-api-key:latest,TELEMETRY_API_KEY=telemetry-api-key:latest'
    waitFor: ['push-tagged']

  # Step 4: Verify deployment health
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'verify-health'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e

        echo "Waiting for service to be ready..."
        sleep 10

        SVC_URL=$$(gcloud run services describe core-infrastructure --region=${_REGION} --format='value(status.url)')
        echo "Service URL: $$SVC_URL"

        # Health check
        echo "Running health check..."
        HEALTH_RESPONSE=$$(curl -s "$$SVC_URL/health")
        HEALTH_STATUS=$$(echo "$$HEALTH_RESPONSE" | jq -r '.status')

        if [ "$$HEALTH_STATUS" != "ok" ] && [ "$$HEALTH_STATUS" != "degraded" ]; then
          echo "Health check failed: $$HEALTH_RESPONSE"
          exit 1
        fi
        echo "Health check passed: $$HEALTH_STATUS"

        # Ready check
        echo "Running readiness check..."
        READY_RESPONSE=$$(curl -s "$$SVC_URL/ready")
        READY_STATUS=$$(echo "$$READY_RESPONSE" | jq -r '.ready')

        if [ "$$READY_STATUS" != "true" ]; then
          echo "Warning: Readiness check returned: $$READY_RESPONSE"
        else
          echo "Readiness check passed"
        fi

        # Verify DecisionEvent emission (integration health)
        echo "Verifying DecisionEvent emission..."
        DECISION_RESPONSE=$$(curl -s -X POST "$$SVC_URL/health/integrations" \
          -H "Content-Type: application/json" \
          -d '{"integrations": [], "timeout_ms": 5000}')

        DECISION_TYPE=$$(echo "$$DECISION_RESPONSE" | jq -r '.decision_event.decision_type')

        if [ "$$DECISION_TYPE" != "integration_health_signal" ]; then
          echo "DecisionEvent verification failed: $$DECISION_RESPONSE"
          exit 1
        fi
        echo "DecisionEvent verification passed: $$DECISION_TYPE"

        echo ""
        echo "=============================================="
        echo " Phase 6 Core Infrastructure deployed successfully!"
        echo " Service URL: $$SVC_URL"
        echo "=============================================="
    waitFor: ['deploy']

substitutions:
  _REGION: 'us-central1'
  _PLATFORM_ENV: 'dev'
  _RUVECTOR_SERVICE_URL: 'https://ruvector-service.run.app'
  _TELEMETRY_ENDPOINT: 'https://llm-observatory.run.app'
  _IMAGE_TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - 'gcr.io/$PROJECT_ID/core-infrastructure:${_IMAGE_TAG}'
  - 'gcr.io/$PROJECT_ID/core-infrastructure:latest'

timeout: '1200s'
